In [ ]:
import numpy as np

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
np.zeros(((3,3,3)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
np.random.rand(5)

array([0.64807028, 0.91569105, 0.64573718, 0.96854846, 0.11620638])

In [ ]:
np.arange(5,dtype='float')

array([0., 1., 2., 3., 4.])

In [ ]:
np.random.randint(1,10)

3

In [ ]:
ls=[1,33,3,4,35,6,7,8]
l=[]
c=[]
for i in range(int(len(ls))) :
  for j in ls:




[None, None, None, None, None, None, None, None]


In [ ]:
a=np.array([1,2,5,4])
b=np.array([6,2,9,4])
print(a==b)

[False  True False  True]


In [ ]:
np.array_equal(a,b)

False

In [ ]:
c=np.array([1,2,5,4])
np.array_equal(a,c)

True

In [ ]:
a=np.array([1,0,0,1],dtype='bool')
b=np.array([0,1,0,1],dtype='bool')

In [ ]:
np.logical_or(a,b)

array([ True,  True, False,  True])

In [ ]:
np.logical_and(a,b)

array([False, False, False,  True])

In [ ]:
np.logical_not(a,b)

array([False,  True,  True, False])

In [ ]:
np.exp(a)

array([2.719, 1.   , 1.   , 2.719], dtype=float16)

In [ ]:
d=np.array([2,3,4,3])
e=np.array([3,2,4])
print(d+e)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
x=np.arange(10)
print(sum(x))

45


In [ ]:
y=np.array([[1,2],[3,4]])
print(y)

[[1 2]
 [3 4]]


In [ ]:
print("*"*100)

****************************************************************************************************


In [ ]:
print(y.T)

[[1 3]
 [2 4]]


In [ ]:
print(y.sum(axis=0))

[4 6]


In [ ]:
print(y.sum(axis=1))

[3 7]


In [ ]:
print(y.max())

4


In [ ]:
print(y.argmin())

0


2.5

array([2., 5.])

In [ ]:
np.std(x)

2.8722813232690143

In [ ]:
l=[1,2,3,4,5,6,7]
np.array(l)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
x=np.arange(1,10)
print(x.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a=np.array([[2,5,1],[4,43,2]])


In [ ]:
np.sort(a,axis=0)
np.sort(a,axis=1)

array([[ 1,  2,  5],
       [ 2,  4, 43]])

In [ ]:
a.flatten()


array([ 1,  2,  5,  2,  4, 43])

In [ ]:
import calendar as c
date=c.calendar(2017,2)
date

'                                  2017\n\n      January                   February                   March\nMo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su\n                   1             1  2  3  4  5             1  2  3  4  5\n 2  3  4  5  6  7  8       6  7  8  9 10 11 12       6  7  8  9 10 11 12\n 9 10 11 12 13 14 15      13 14 15 16 17 18 19      13 14 15 16 17 18 19\n16 17 18 19 20 21 22      20 21 22 23 24 25 26      20 21 22 23 24 25 26\n23 24 25 26 27 28 29      27 28                     27 28 29 30 31\n30 31\n\n       April                      May                       June\nMo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su\n                1  2       1  2  3  4  5  6  7                1  2  3  4\n 3  4  5  6  7  8  9       8  9 10 11 12 13 14       5  6  7  8  9 10 11\n10 11 12 13 14 15 16      15 16 17 18 19 20 21      12 13 14 15 16 17 18\n17 18 19 20 21 22 23      22 23 24 25 26 27 28      19 20 21 22 23 24 25\n24 25 26

                                  2017

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                   1             1  2  3  4  5             1  2  3  4  5
 2  3  4  5  6  7  8       6  7  8  9 10 11 12       6  7  8  9 10 11 12
 9 10 11 12 13 14 15      13 14 15 16 17 18 19      13 14 15 16 17 18 19
16 17 18 19 20 21 22      20 21 22 23 24 25 26      20 21 22 23 24 25 26
23 24 25 26 27 28 29      27 28                     27 28 29 30 31
30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2       1  2  3  4  5  6  7                1  2  3  4
 3  4  5  6  7  8  9       8  9 10 11 12 13 14       5  6  7  8  9 10 11
10 11 12 13 14 15 16      15 16 17 18 19 20 21      12 13 14 15 16 17 18
17 18 19 20 21 22 23      22 23 24 25 26 27 28      19 20 21 22 23 24 25
24 25 26 27 28 29 30      

In [ ]:
import datetime as dt
np.arange(dt.datetime(2017,3,1),dt.datetime(2018,3,1),dtype='datetime64[D]')

In [ ]:
import pandas as pd
import numpy as np
data=np.array(['a','b','c','d'])
s=pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: object


In [ ]:
data=np.array(['a','b','c','d'])#assigning index manually
s=pd.Series(data,index=[100,200,300,400])
print(s)

100    a
200    b
300    c
400    d
dtype: object


In [ ]:
data={'A':0,'B':1,'C':3,'D':4}#using dictionaries
pd.Series(data)

A    0
B    1
C    3
D    4
dtype: int64

In [ ]:
data={'A':0,'B':1,'C':3}
s=pd.Series(data,index=['B','C','D','A'])
print(s)

B    1.0
C    3.0
D    NaN
A    0.0
dtype: float64


In [ ]:
#scalar
s=pd.Series(5,index=[0,1,2,3])
print(s)

0    5
1    5
2    5
3    5
dtype: int64


In [ ]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
s[2]

3

In [ ]:
s[:3]

a    1
b    2
c    3
dtype: int64

In [ ]:
print(s['a'])

1


In [ ]:
print(s[['a','b','c','d']])

a    1
b    2
c    3
d    4
dtype: int64


create a integer list and convert into float datatype

---



In [ ]:
li=[1,2,3,4,5,6]
d=pd.Series(li,dtype=float)
print(d)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
dtype: float64


In [ ]:
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [ ]:
data=[1,2,3,4,5]
df=pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [ ]:
data=[["shabbu",34],["narendra",55],["bhavana",23]]
df=pd.DataFrame(data,columns=['name','age'],dtype=float)
print(df)

       name   age
0    shabbu  34.0
1  narendra  55.0
2   bhavana  23.0


<ipython-input-22-29a81fe6a5ec>:2: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df=pd.DataFrame(data,columns=['name','age'],dtype=float)


In [ ]:
data={'name':['suman','shannu'],'age':[24,55]}
pd.DataFrame(data,columns=['name','age'],index=['rank1','rank2'])

name  age
rank1   suman   24
rank2  shannu   55

In [ ]:
import pandas as pd
data=[{'a':1,'b':2},{'a':10,'b':20,'c':30}]
print(pd.DataFrame(data))

    a   b     c
0   1   2   NaN
1  10  20  30.0


In [ ]:
import pandas as pd
#The following examples shows how to create a Dataframe by passing a list of dictionaries and the row indices
data=[{'a':1,'b':2},{'a':10,'b':20,'c':30}]
print(pd.DataFrame(data,index=['first','second']))

         a   b     c
first    1   2   NaN
second  10  20  30.0


In [ ]:
data=[{'a':1,'b':2},{'a':10,'b':20,'c':30}]
#with two column indices, values same as dictionary keys
df1=pd.DataFrame(data,index=['first','second'],columns=['a','b'])
#with two column indices,with one index,with othername
df2=pd.DataFrame(data,index=['first','second'],columns=['a','b1'])
print(df1)
print(df2)

         a   b
first    1   2
second  10  20
         a  b1   b
first    1 NaN   2
second  10 NaN  20


In [ ]:
df3=pd.DataFrame(data,index=['first','second'],columns=['a','b1','b'])
df3

a  b1   b
first    1 NaN   2
second  10 NaN  20

In [ ]:
df2=pd.DataFrame(data,index=['first','second'],columns=['a','b1'])
df2


a  b1
first    1 NaN
second  10 NaN

In [ ]:
d={'one':pd.Series([1,2,3],index=['a','b','c']),'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df =pd.DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [ ]:
d={'one':pd.Series([1,2,3],index=['a','b','c']),'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df =pd.DataFrame(d)
#adding a new column to an existing DataFrame onject with column label by passing new series
print("adding a new colun by passing as series: ")
df['three']=pd.Series([10,20,30],index=['a','b','c'])
df

adding a new colun by passing as series: 


one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [ ]:
df['four']=df['one']+df['two']
df

one  two  three  four
a  1.0    1   10.0   2.0
b  2.0    2   20.0   4.0
c  3.0    3   30.0   6.0
d  NaN    4    NaN   NaN

In [ ]:
print("deleting the first column using del function")
del df['one']
df

deleting the first column using del function


two  three  four
a    1   10.0   2.0
b    2   20.0   4.0
c    3   30.0   6.0
d    4    NaN   NaN

In [ ]:
#using pop function
df.pop('two')
df

three  four
a   10.0   2.0
b   20.0   4.0
c   30.0   6.0
d    NaN   NaN

In [ ]:
d={'one':pd.Series([1,2,3],index=['a','b','c']),'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df =pd.DataFrame(d)
print(df.loc['b'])

one    2.0
two    2.0
Name: b, dtype: float64


In [ ]:
d={'one':pd.Series([1,2,3],index=['a','b','c']),'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df =pd.DataFrame(d)
print(df.iloc[0])

one    1.0
two    1.0
Name: a, dtype: float64


In [ ]:
df[2:4]

one  two
c  3.0    3
d  NaN    4

In [ ]:
#add new rows to a DataFrame using the append function. This function will append the rows at the end.
df=pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
df1=pd.DataFrame([[5,6],[6,7]],columns=['a','b'])
df

a  b
0  1  2
1  3  4

In [ ]:
df1

a  b
0  5  6
1  6  7

In [ ]:
df.drop(0)

a  b
1  3  4

In [ ]:
df=pd.read_csv("/content/heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [ ]:
df.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [ ]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [ ]:
df['age']

0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

16473